У цьому домашньому завданні ми будемо працювати з набором даних Tips. Нижче інформація про нього.

**Про датасет:**

Tips - це датасет, який містить інформацію про рахунки та чайові в ресторані.

**Колонки датасету:**
- `total_bill` - загальна сума рахунку (долари)
- `tip` - розмір чайових (долари)
- `sex` - стать відвідувача (Male/Female)
- `smoker` - чи курить (Yes/No)
- `day` - день тижня (Thur/Fri/Sat/Sun)
- `time` - час відвідування (Lunch/Dinner)
- `size` - розмір групи (кількість людей)

**Джерело:** Оригінальні дані зібрані в одному з американських ресторанів у 1990-х роках. Скачати і переглянути набір даних можна тут: https://www.kaggle.com/datasets/sakshisatre/tips-dataset

А також ми вже вивантажили файл з даними і завантажили вам у Матеріали до цього модуля.




**1. Завантаження та огляд**

Завантажте датасет Tips (Чайові) з файла у матеріалах `tips.csv`.

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перші 5 рядків
- Розмір датасету (shape)
- Назви всіх колонок
- Інформацію про типи даних (info)

In [1]:
# Імпорт бібліотеки pandas під скороченим псевдонімом pd
import pandas as pd

# Завантаження набору даних Tips з файлу csv
df = pd.read_csv('tips.csv')

In [2]:
# Виведення перших 5 рядків набору даних Tips
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
# Виведення розміру набору даних Tips
df.shape

(244, 7)

In [4]:
# Виведення назв усіх колонок набору даних Tips
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [5]:
# Виведення інформації про типи даних набору даних Tips
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

**2. Базова вибірка даних**

Виберіть та виведіть (кожен пункт оцінюється в 0.5 бала):
- Колонку `total_bill` (загальний рахунок)
- Колонки `total_bill` та `tip` (чайові) разом
- Перші 10 рядків
- Рядок з індексом 5

In [6]:
# Вибірка та виведення колонки total_bill (загальний рахунок) набору даних Tips
total_bill = df[['total_bill']]
total_bill

     total_bill
0         16.99
1         10.34
2         21.01
3         23.68
4         24.59
..          ...
239       29.03
240       27.18
241       22.67
242       17.82
243       18.78

[244 rows x 1 columns]

In [7]:
# Вибірка та виведення колонок total_bill (загальний рахунок) та tip (чайові) набору даних Tips
total_bill_and_tips = df[['total_bill', 'tip']]
total_bill_and_tips

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [8]:
# Вибірка та виведення перших 10 рядків набору даних Tips
first_10_rows = df.head(10)
first_10_rows

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [9]:
# Вибірка та виведення рядка з індексом 5 набору даних Tips
row_ind_5 = df.iloc[[5]]
row_ind_5

   total_bill   tip   sex smoker  day    time  size
5       25.29  4.71  Male     No  Sun  Dinner     4

**3. Фільтрація даних**

Відфільтруйте повний набір даних та виведіть (кожен пункт оцінюється в 0.5 бала):
- Всі рахунки більше 20 доларів (`total_bill > 20`)
- Всі відвідувачі-жінки (`sex == 'Female'`)
- Рахунки на вечерю (`time == 'Dinner'`)
- Рахунки на вечерю з сумою чеку більше 30 доларів

Для виведення результатів фільтрації:
- зберегти результат у окрему змінну
- показати кількість записів у відфільтрованому наборі
- вивести перші 5 записів відфільтрованого набору.

In [10]:
# Фільтрація всіх записів з рахунками більше 20 доларів (total_bill > 20) набору даних Tips

# Збереження всіх записів з рахунками більше 20 доларів набору даних Tips в окрему змінну
total_bill_above_20 = df[df['total_bill'] > 20]

# Показ кількості записів у відфільтрованому наборі
print(f"Кількість записів з рахунками більше 20 доларів: {len(total_bill_above_20)}")

# Виведення перших 5 записів відфільтрованого набору
total_bill_above_20.head()

Кількість записів з рахунками більше 20 доларів: 97

   total_bill   tip     sex smoker  day    time  size
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
7       26.88  3.12    Male     No  Sun  Dinner     4

In [11]:
# Фільтрація всіх записів з відвідувачами-жінками (sex == 'Female') набору даних Tips

# Збереження всіх записів з відвідувачами-жінками набору даних Tips в окрему змінну
sex_female = df[df['sex'] == 'Female']

# Показ кількості записів у відфільтрованому наборі
print(f"Кількість записів з відвідувачами-жінками: {len(sex_female)}")

# Виведення перших 5 записів відфільтрованого набору
sex_female.head()

Кількість записів з відвідувачами-жінками: 87

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
11       35.26  5.00  Female     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2
16       10.33  1.67  Female     No  Sun  Dinner     3

In [12]:
# Фільтрація всіх записів з рахунками на вечерю (time == 'Dinner') набору даних Tips

# Збереження всіх записів з рахунками на вечерю набору даних Tips в окрему змінну
time_dinner = df[df['time'] == 'Dinner']

# Показ кількості записів у відфільтрованому наборі
print(f"Кількість записів з рахунками на вечерю: {len(time_dinner)}")

# Виведення перших 5 записів відфільтрованого набору
time_dinner.head()

Кількість записів з рахунками на вечерю: 176

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [13]:
# Фільтрація всіх записів з рахунками на вечерю більше 30 доларів набору даних Tips

# Збереження всіх записів з рахунками на вечерю більше 30 доларів набору даних Tips в окрему змінну
time_dinner_and_total_bill_above_30 = df[(df['time'] == 'Dinner') & (df['total_bill'] > 30)]

# Показ кількості записів у відфільтрованому наборі
print(f"Кількість записів з рахунками на вечерю більше 30 доларів: {len(time_dinner_and_total_bill_above_30)}")

# Виведення перших 5 записів відфільтрованого набору
time_dinner_and_total_bill_above_30.head()

Кількість записів з рахунками на вечерю більше 30 доларів: 27

    total_bill   tip     sex smoker  day    time  size
11       35.26  5.00  Female     No  Sun  Dinner     4
23       39.42  7.58    Male     No  Sat  Dinner     4
39       31.27  5.00    Male     No  Sat  Dinner     3
44       30.40  5.60    Male     No  Sun  Dinner     4
47       32.40  6.00    Male     No  Sun  Dinner     4

---

**4. Описова статистика**

Обчисліть (кожен пункт оцінюється в 0.5 бала):
- Середній розмір рахунку на всьому наборі даних
- Максимальні чайові
- Кількість пропущених значень у всіх колонках
- Скільки в наборі даних рахунків за обіди і за вечері

In [14]:
# Обчислення середнього розміру рахунку на наборі даних Tips
total_bill_mean = df['total_bill'].mean()
print(f"Середній розмір рахунку: {total_bill_mean}")

Середній розмір рахунку: 19.78594262295082

In [15]:
# Обчислення максимальних чайових на наборі даних Tips
max_tip = df['tip'].max()
print(f"Максимальні чайові: {max_tip}")

Максимальні чайові: 10.0

In [95]:
# Обчислення кількості пропущених значень у всіх колонках на наборі даних Tips
null_counted = df.isnull().sum()
print("Кількість пропущених значень у всіх колонках:")
null_counted

Кількість пропущених значень у всіх колонках:

total_bill        0
tip               0
sex               0
smoker            0
day               0
time              0
size              0
tip_percentage    0
dtype: int64

In [26]:
# Обчислення кількості рахунків за обіди і за вечері на наборі даних Tips

# Фільтрація всіх записів з рахунками за обіди і за вечері набору даних Tips
lunches_and_dinners = df[df['time'].isin(['Lunch', 'Dinner'])]
display(lunches_and_dinners)

# Обчислення кількості рахунків у відфільтрованому наборі
print(f"Кількість записів з рахунками за обіди і за вечері: {len(lunches_and_dinners)}")

     total_bill   tip     sex smoker   day    time  size  tip_percentage
0         16.99  1.01  Female     No   Sun  Dinner     2        0.059447
1         10.34  1.66    Male     No   Sun  Dinner     3        0.160542
2         21.01  3.50    Male     No   Sun  Dinner     3        0.166587
3         23.68  3.31    Male     No   Sun  Dinner     2        0.139780
4         24.59  3.61  Female     No   Sun  Dinner     4        0.146808
..          ...   ...     ...    ...   ...     ...   ...             ...
239       29.03  5.92    Male     No   Sat  Dinner     3        0.203927
240       27.18  2.00  Female    Yes   Sat  Dinner     2        0.073584
241       22.67  2.00    Male    Yes   Sat  Dinner     2        0.088222
242       17.82  1.75    Male     No   Sat  Dinner     2        0.098204
243       18.78  3.00  Female     No  Thur  Dinner     2        0.159744

[244 rows x 8 columns]

Кількість записів з рахунками за обіди і за вечері: 244

---

**5. Статистика із групуванням**

Обчисліть (кожен пункт оцінюється в 0.5 бала):
- Середній рахунок за статтю (groupby `sex`)
- Середні чайові за днем тижня (groupby `day`)
- Скільки відвідувачів у кожен день

In [27]:
# Обчислення середнього рахунку за статтю (groupby sex) на наборі даних Tips
mean_total_bill_by_class = df.groupby('sex')[['total_bill']].mean()
print("Середній рахунок за статтю:")
mean_total_bill_by_class

Середній рахунок за статтю:

        total_bill
sex
Female   18.056897
Male     20.744076

In [28]:
# Обчислення середніх чайових за днем тижня (groupby day) на наборі даних Tips
mean_tip_by_day = df.groupby('day')[['tip']].mean()
print("Середні чайові за днем тижня:")
mean_tip_by_day

Середні чайові за днем тижня:

           tip
day
Fri   2.734737
Sat   2.993103
Sun   3.255132
Thur  2.771452

In [29]:
# Обчислення кількості відвідувачів у кожен день тижня на наборі даних Tips
sum_size_by_day = df.groupby('day')[['size']].sum()
print("Кількість відвідувачів за днем тижня:")
sum_size_by_day

Кількість відвідувачів за днем тижня:

      size
day
Fri     40
Sat    219
Sun    216
Thur   152

---

**6. Створення нової колонки**

Створіть нову колонку `tip_percentage` - відсоток чайових від загальної суми рахунку.
Виведіть перші 10 рядків з новою колонкою.

In [30]:
# Створення нової колонки tip_percentage (відсоток чайових від загальної суми рахунку) в наборі даних Tips
df['tip_percentage'] = df['tip'] / df['total_bill']

# Виведення перших 10 рядків з новою колонкою
df.head(10)

   total_bill   tip     sex smoker  day    time  size  tip_percentage
0       16.99  1.01  Female     No  Sun  Dinner     2        0.059447
1       10.34  1.66    Male     No  Sun  Dinner     3        0.160542
2       21.01  3.50    Male     No  Sun  Dinner     3        0.166587
3       23.68  3.31    Male     No  Sun  Dinner     2        0.139780
4       24.59  3.61  Female     No  Sun  Dinner     4        0.146808
5       25.29  4.71    Male     No  Sun  Dinner     4        0.186240
6        8.77  2.00    Male     No  Sun  Dinner     2        0.228050
7       26.88  3.12    Male     No  Sun  Dinner     4        0.116071
8       15.04  1.96    Male     No  Sun  Dinner     2        0.130319
9       14.78  3.23    Male     No  Sun  Dinner     2        0.218539

---

**7. Сортування**

Відсортуйте датасет і виведіть результат сортування в кожному випадку окремо (кожен пункт оцінюється в 0.5 бала):
- За розміром рахунку (зростання)
- За чайовими (спадання)

Додатково виведіть топ-5 найбільших чайових використовуючи метод `nlargest`.

In [31]:
# Сортування набору даних Tips за розміром рахунку (за зростанням)
df_sorted_total_bill = df.sort_values('total_bill')
df_sorted_total_bill

     total_bill    tip     sex smoker   day    time  size  tip_percentage
67         3.07   1.00  Female    Yes   Sat  Dinner     1        0.325733
92         5.75   1.00  Female    Yes   Fri  Dinner     2        0.173913
111        7.25   1.00  Female     No   Sat  Dinner     1        0.137931
172        7.25   5.15    Male    Yes   Sun  Dinner     2        0.710345
149        7.51   2.00    Male     No  Thur   Lunch     2        0.266312
..          ...    ...     ...    ...   ...     ...   ...             ...
182       45.35   3.50    Male    Yes   Sun  Dinner     3        0.077178
156       48.17   5.00    Male     No   Sun  Dinner     6        0.103799
59        48.27   6.73    Male     No   Sat  Dinner     4        0.139424
212       48.33   9.00    Male     No   Sat  Dinner     4        0.186220
170       50.81  10.00    Male    Yes   Sat  Dinner     3        0.196812

[244 rows x 8 columns]

In [32]:
# Сортування набору даних Tips за розміром чайових (за спаданням)
df_sorted_tip_desc = df.sort_values('tip', ascending = False)
df_sorted_tip_desc

     total_bill    tip     sex smoker   day    time  size  tip_percentage
170       50.81  10.00    Male    Yes   Sat  Dinner     3        0.196812
212       48.33   9.00    Male     No   Sat  Dinner     4        0.186220
23        39.42   7.58    Male     No   Sat  Dinner     4        0.192288
59        48.27   6.73    Male     No   Sat  Dinner     4        0.139424
141       34.30   6.70    Male     No  Thur   Lunch     6        0.195335
..          ...    ...     ...    ...   ...     ...   ...             ...
0         16.99   1.01  Female     No   Sun  Dinner     2        0.059447
236       12.60   1.00    Male    Yes   Sat  Dinner     2        0.079365
111        7.25   1.00  Female     No   Sat  Dinner     1        0.137931
67         3.07   1.00  Female    Yes   Sat  Dinner     1        0.325733
92         5.75   1.00  Female    Yes   Fri  Dinner     2        0.173913

[244 rows x 8 columns]

In [33]:
# Виведення топ-5 найбільших чайових, використовуючи метод nlargest
largest_tips = df.nlargest(5, 'tip')
largest_tips

     total_bill    tip   sex smoker   day    time  size  tip_percentage
170       50.81  10.00  Male    Yes   Sat  Dinner     3        0.196812
212       48.33   9.00  Male     No   Sat  Dinner     4        0.186220
23        39.42   7.58  Male     No   Sat  Dinner     4        0.192288
59        48.27   6.73  Male     No   Sat  Dinner     4        0.139424
141       34.30   6.70  Male     No  Thur   Lunch     6        0.195335